pipeline:
  stages:
    - steps:
        - name: Build
          id: Build
          build:
            uses: gitCloneStep
            with:
              connector: demo_github
              repo_name: https://github.com/Bapujee1015/Demo
              build:
                target: Git Branch
                branch: main
              pr_merge_strategy: Source Branch
              depth: "50"
              lfs_enabled: false
              debug: false
              fetch_tags: false
              insecure: false
        - name: step1
          run:
            shell: bash
            script: "pwd

              echo \"Hellow-World\""
          id: step1
        - name: push image to dockerhub
          id: push_image_to_dockerhub
          build:
            uses: buildAndPushToDocker
            with:
              connector: connector_Docker
              repo: bapujee105/hello-app
              tags:
                - v3
              caching: false
              build_mode: build_and_push
              plugin_cloud: buildx
              dockerfile: Demo/hello-app/Dockerfile
              context: Demo/hello-app
